package sketchupblocks.base;

/**
 * CameraEvent is a wrapper for the useful data generated by a camera event from ReacTIVision.
 * It contains the id of the camera that fired it, the x, y position of the fiducial observed in that camera's viewing plane, 
 * the fiducial's rotation and rotation velocity, the horizontal velocity of the fiducial and the id of the observed fiducial.
 * This also wraps the type of event that occurred, namely ADD, REMOVE or UPDATE
 * 
 * @author cravingoxygen
 *
 */
public class CameraEvent
{

	/**
	 * The type of camera event observed
	 */
	public enum EVENT_TYPE
	{

		/**
		 * Fiducials that have not yet been seen or have been removed from the scene by a camera running ReacTIVision will have EVENT_TYPE ADD
		 */
		ADD,

		/**
		 * Fiducials that are no longer visible in the scene by a camera running  ReacTIVision will have EVENT_TYPE REMOVE
		 */
		REMOVE,
		
		/**
		 * Fiducials that were already in the scene, but are observed at a new location in the scene will have EVENT_TYPE UPDATE
		 */
		UPDATE
	}
	
	/**
	 * The id of the camera that observed the camera event.
	 */
	public int cameraID;
	/**
	 * The x co-ordinate of the observed fiducial center (relative to the camera's viewing frame)
	 */
	public float x;
	/**
	 * The y co-ordinate of the observed fiducial center (relative to the camera's viewing frame)
	 */
	public float y;
	/**
	 * The rotation of the observed fiducial center (relative to the fiducial's natural orientation i.e. up)
	 */
	public float rotation;
	/**
	 * The rate at which the rotation of the observed fiducial is changing
	 */
	public float rotAcceleration;
	/**
	 * The rate at which the observed fiducial is rotating
	 */
	public float rotVelocity;
	/**
	 * The velocity at which the observed fiducial is moving horizontally
	 */
	public float xVelocity;

	/**
	 * The type of the observed camera event.
	 */
	public EVENT_TYPE type;

	/**
	 * The id of the observed fiducial.
	 */
	public int fiducialID;
}